[package]
name = "solar-client"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
morningstar = { path = "../../morningstar" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.12"
chrono = "0.4"
libflate = "0.1"
log = "0.4"
