[package]
name = "solar"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
daemonize = "0.3"
error-chain = "0.12"
libmodbus-rs = "0.8"
log = "0.4"
morningstar = {path = "../../morningstar"}
rppal = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
simple_logger = "1.0"
solar-client = {path = "../solar-client"}
structopt = "0.2"
syslog = "4.0"
chrono = "0.4"
libflate = "0.1"
